### PR TITLE
Translation to sr_RS

### PR DESCRIPTION
**Pull request by knjigor**

### CODE REVIEW

**Review by mtub — COMMENTED** [review]
This pull request points to a problem we have with the sr_SR locale files. Tagging @asmecher.

OJS has used sr_SR for "Serbian" for some time now, but this is the wrong code. Serbia is "RS", so it should be sr_RS.

But then there is a Latin and a Cyrillic version, and @knjigor has provided us with both versions. But we have no means to have those two versions in our naming scheme, they would both have to be sr_RS.

We could think about sr_RS-latin or sr_latin_RS, but this would be a totally new naming scheme in our locale files.

We should think about renaming sr_SR to sr_RS in all applications, but we also need to think about a solution for latin vs cyrillic.

**Comment by asmecher** [comment]
Interesting. There are several parts of the code that assume `xx_YY` and may not behave well if we start changing that convention to include refinements, but not so many that we couldn't grep/fix them. We're also considering ways to support multilingual user names -- the Latin vs. Cyrillic distinction is a commonly cited example of why it's necessary -- and I think the character set is the defining distinction for this feature add too (think e.g. Latin vs. Chinese, Latin vs. Japanese, etc.) Tagging @ctgraham in since this is an area of interest for him too.

**Comment by ctgraham** [comment]
Japanese is also an interesting case.  Generally the text will be a mixture of kanji and hiragana/katakana.  But what if a Japanese scholar were to internationalize a name to the en_US locale?  Would the scholar default to romanji, or to latin characters without the diacritics?  Would we, or any downstream integrations, care?  I imagine the romanji would be equally appropriate in the ja_JP locale, particularly in the case of a native English speaker entering a Japanese form of the name.

**Comment by asmecher** [comment]
Speaking as a relative neophyte to non-Latin character sets, I'd expect the author would have the discretion to choose how their name was transcribed -- and I can't imagine they would want the flexibility to do it in more than one way per "class" of languages (whether that corresponds well to character set, I'm not sure).

**Comment by ctgraham** [comment]
If I'm reading you correctly, at least one forum user had the exact opposite expectation, namely, requiring the user to re-enter their name in any variant character set offered by the journal:
http://forum.pkp.sfu.ca/t/dual-language-journal/13157/16?u=ctgraham

**Comment by ctgraham** [comment]
I think what we're describing here is analogous to the way Microsoft handles locale code pages:
https://msdn.microsoft.com/en-us/library/hzz3tw78.aspx

**Comment by asmecher** [comment]
@ctgraham, that's not quite what I meant -- whether it's what I said is another question :) -- what I'm imagining is that we'd define "classes" of languages, breaking them up roughly into character set -- Cyrillic (Russian, Ukrainian, etc), Latin (English, Czech, Spanish...), Chinese Big-5, Chinese Simplified, etc. When a journal's setup spans more than one class of languages, then we'd have one input for each one.

I deliberately choose big5/simplified as separate classes here, because I suspect journals operating in both may want to permit users to enter a name in each, despite them belonging to the same language.

(The easiest thing to do [besides nothing] is to permit an entry for each language, but that'll be jarring for 99% of our users. And if we get the groupings wrong, administrators ought to be able to change the groupings by editing the locale registry at worst.)

I'm improvising here for the sake of airing out issues -- I'll bet this is a solved distinction and I'm trampling all over it without sufficient background in non-Latin languages.

**Comment by mtub** [comment]
I am closing this PR as we will not merge the files as they are. Discussion on script variants: see https://github.com/pkp/pkp-lib/issues/1858

**Pull request closed without merging**
